version: 2

jobs:
  test:
    docker:
    - image: cimg/go:1.18
      environment:
        GO111MODULE: "on"
        GOLANGCI_VERSION: "v1.45.2"
    steps:
    - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s ${GOLANGCI_VERSION}
    - run: mv ./bin/golangci-lint $GOPATH/bin/ && rm -rf bin
    - checkout
    - run: go mod download
    - run: make lint
    - run: make test
    - run: make build

workflows:
  version: 2
  test:
    jobs:
      - test
